# Generated by Django 3.2.15 on 2022-10-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_ads_js', models.TextField(blank=True, help_text='Paste the script snippet generated for auto ads from adsense.', null=True, verbose_name='Auto Ads script')),
                ('auto_ads_enable', models.BooleanField(default=False, help_text='Enable this button to use auto ads.', verbose_name='Enable Auto ads')),
                ('in_article_ad_js', models.TextField(blank=True, help_text='Paste the script snippet generated for in-article ads from adsense.', null=True, verbose_name='In-article ads script')),
                ('in_article_ad_enable', models.BooleanField(default=False, help_text='Enable this button to use in-article ads.(auto ads should be disabled).', verbose_name='Enable In-article ads')),
                ('sidebar_ad_js', models.TextField(blank=True, help_text='Paste the script snippet generated for display ads from adsense.', null=True, verbose_name='Sidebar ads script')),
                ('sidebar_ad_enable', models.BooleanField(default=False, help_text='Enable this button to use sidebar ads.(auto ads should be disabled).', verbose_name='Enable Sidebar ads')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Google Adsense',
            },
        ),
    ]
