# Generated by Django 3.2.15 on 2022-10-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='The base url for the site.', verbose_name='Base URL')),
                ('tagline', models.CharField(blank=True, help_text='The tagline of your organisation.', max_length=255, null=True, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, help_text='A short description about your organisation.', max_length=500, null=True, verbose_name='Description')),
                ('contact_phone', models.CharField(blank=True, help_text='The contact phone number of your organisation.', max_length=15, null=True, verbose_name='Phone number')),
                ('contact_address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Contact Address')),
                ('contact_email', models.EmailField(blank=True, help_text='The contact email address of your organisation.', max_length=100, null=True, verbose_name='Contact Email')),
                ('twitter_link', models.URLField(blank=True, help_text="Paste the link of your organisation's Twitter page.", max_length=255, null=True, verbose_name='Twitter Link')),
                ('facebook_link', models.URLField(blank=True, help_text="Paste the link of your organisation's Facebook page/account.", max_length=255, null=True, verbose_name='Facebook Link')),
                ('instagram_link', models.URLField(blank=True, help_text="Paste the link of your organisation's Instagram page.", max_length=255, null=True, verbose_name='Instagram Link')),
                ('youtube_link', models.URLField(blank=True, help_text="Paste the link of your organisation's Youtube channel.", max_length=255, null=True, verbose_name='Youtube Link')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tracking_id', models.CharField(blank=True, help_text='Your Google "Universal Analytics" tracking ID (begins with "UA-")', max_length=255, verbose_name='UA Tracking ID')),
                ('ga_g_tracking_id', models.CharField(blank=True, help_text='Your Google Analytics 4 tracking ID (begins with "G-")', max_length=255, verbose_name='Google Tracking ID')),
                ('ga_track_button_clicks', models.BooleanField(default=False, help_text='Track all button clicks using Google Analytics event tracking. Event tracking details can be specified in each button’s advanced settings options.', verbose_name='Track button clicks')),
                ('gtm_id', models.CharField(blank=True, help_text='Begins with "GTM-"', max_length=255, verbose_name='Google Tag Manager ID')),
                ('head_scripts', models.TextField(blank=True, help_text='Add tracking scripts between the <head> tags.', null=True, verbose_name='<head> tracking scripts')),
                ('body_scripts', models.TextField(blank=True, help_text='Add tracking scripts toward closing <body> tag.', null=True, verbose_name='<body> tracking scripts')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Google Tracking',
            },
        ),
    ]
